<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\ProductImage;
use App\Models\ProductVariant;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $productsData = [
            // ==========================================
            // 1. GIÀY BÓNG ĐÁ (Category ID: 1)
            // ==========================================
            [
                'id' => 1,
                'name' => 'Nike Phantom GX Elite FG',
                'brand' => 'Nike',
                'category_id' => 1,
                'price' => 4290000,
                'old_price' => 4990000,
                'tag' => 'BEST SELLER',
                'stock' => 25,
                'sku' => 'STR-NK-PGX-01',
                'image_url' => 'https://images.unsplash.com/photo-1511886929837-354d827aae26?auto=format&fit=crop&w=900&q=85',
                'images' => [
                    'https://images.unsplash.com/photo-1511886929837-354d827aae26?auto=format&fit=crop&w=900&q=85',
                    'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=900&q=85',
                ],
                'colors' => ['Volt', 'Black'],
                'sizes' => ['39', '40', '41', '42', '43'],
                'description' => 'Đôi giày kiểm soát bóng thế hệ mới với upper Flyknit mềm, kết cấu Gripknit bám bóng đỉnh cao trong mọi điều kiện thời tiết.',
            ],
            [
                'id' => 2,
                'name' => 'Adidas Predator Accuracy.1 FG',
                'brand' => 'Adidas',
                'category_id' => 1,
                'price' => 3890000,
                'old_price' => 4490000,
                'tag' => 'HOT',
                'stock' => 20,
                'sku' => 'STR-AD-PRED-02',
                'image_url' => 'https://images.unsplash.com/photo-1553778263-73a83bab9b0c?auto=format&fit=crop&w=900&q=85',
                'images' => [
                    'https://images.unsplash.com/photo-1553778263-73a83bab9b0c?auto=format&fit=crop&w=900&q=85',
                    'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=900&q=85',
                ],
                'colors' => ['White', 'Red'],
                'sizes' => ['39', '40', '41', '42', '43'],
                'description' => 'Dòng Predator huyền thoại với công nghệ cao su High-Definition Grip giúp những đường chuyền và cú sút có độ xoáy cực đại.',
            ],
            [
                'id' => 3,
                'name' => 'Puma Future Ultimate FG/AG',
                'brand' => 'Puma',
                'category_id' => 1,
                'price' => 3150000,
                'old_price' => 3750000,
                'tag' => 'NEW',
                'stock' => 22,
                'sku' => 'STR-PM-FUT-03',
                'image_url' => 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=900&q=85',
                'images' => [
                    'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=900&q=85',
                    'https://images.unsplash.com/photo-1511886929837-354d827aae26?auto=format&fit=crop&w=900&q=85',
                ],
                'colors' => ['Blue', 'White'],
                'sizes' => ['39', '40', '41', '42', '43'],
                'description' => 'Công nghệ dải nén FUZIONFIT360 ôm sát mu bàn chân, cho phép bạn chơi bóng có hoặc không có dây buộc với sự linh hoạt tuyệt đối.',
            ],
            [
                'id' => 4,
                'name' => 'Mizuno Morelia Neo IV Beta Japan',
                'brand' => 'Mizuno',
                'category_id' => 1,
                'price' => 5450000,
                'old_price' => 5990000,
                'tag' => 'HOT',
                'stock' => 15,
                'sku' => 'STR-MZ-NEO-04',
                'image_url' => 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?auto=format&fit=crop&w=900&q=85',
                'images' => [
                    'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?auto=format&fit=crop&w=900&q=85',
                    'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=85',
                ],
                'colors' => ['Ruby Red', 'Pearl White'],
                'sizes' => ['39', '40', '41', '42'],
                'description' => 'Chế tác thủ công Made in Japan bằng da Kangaroo siêu mềm cao cấp, trọng lượng siêu nhẹ đem lại cảm giác chạm bóng chân thật đỉnh cao.',
            ],
            [
                'id' => 5,
                'name' => 'Nike Air Zoom Mercurial Superfly 9',
                'brand' => 'Nike',
                'category_id' => 1,
                'price' => 4890000,
                'old_price' => 5390000,
                'tag' => 'NEW',
                'stock' => 18,
                'sku' => 'STR-NK-MERC-05',
                'image_url' => 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=85',
                'images' => [
                    'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=85',
                    'https://images.unsplash.com/photo-1511886929837-354d827aae26?auto=format&fit=crop&w=900&q=85',
                ],
                'colors' => ['Metallic Bronze', 'Black/Gold'],
                'sizes' => ['39', '40', '41', '42', '43'],
                'description' => 'Trang bị bộ đệm Zoom Air 3/4 chiều dài chuyên biệt cho bóng đá, cung cấp lực đẩy bứt tốc vượt bậc cho các cầu thủ tốc độ.',
            ],
            [
                'id' => 6,
                'name' => 'Adidas X Crazyfast.1 TF',
                'brand' => 'Adidas',
                'category_id' => 1,
                'price' => 2790000,
                'old_price' => 3200000,
                'tag' => 'BEST SELLER',
                'stock' => 35,
                'sku' => 'STR-AD-CRAZY-06',
                'image_url' => 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=900&q=85',
                'images' => [
                    'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=900&q=85',
                    'https://images.unsplash.com/photo-1553778263-73a83bab9b0c?auto=format&fit=crop&w=900&q=85',
                ],
                'colors' => ['Solar Red', 'Cloud White'],
                'sizes' => ['39', '40', '41', '42', '43'],
                'description' => 'Đế đinh dăm TF chuyên dụng cho mặt sân cỏ nhân tạo Việt Nam, upper siêu mỏng nhẹ tăng khả năng đảo hướng và phản xạ tốc độ cao.',
            ],
            [
                'id' => 7,
                'name' => 'Nike Tiempo Legend 10 Elite FG',
                'brand' => 'Nike',
                'category_id' => 1,
                'price' => 4590000,
                'old_price' => 5190000,
                'tag' => 'HOT',
                'stock' => 16,
                'sku' => 'STR-NK-TIEMPO-07',
                'image_url' => 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?auto=format&fit=crop&w=900&q=85',
                'images' => [
                    'https://images.unsplash.com/photo-1560769629-975ec94e6a86?auto=format&fit=crop&w=900&q=85',
                    'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=85',
                ],
                'colors' => ['Emerald Teal', 'White'],
                'sizes' => ['39', '40', '41', '42', '43'],
                'description' => 'Chất liệu da nhân tạo FlyTouch Plus tân tiến, êm ái hơn da tự nhiên, kiểm soát bóng chuẩn xác ngay cả dưới trời mưa ẩm.',
            ],
            [
                'id' => 8,
                'name' => 'Puma King Ultimate FG/AG',
                'brand' => 'Puma',
                'category_id' => 1,
                'price' => 2990000,
                'old_price' => 3490000,
                'tag' => 'SALE',
                'stock' => 20,
                'sku' => 'STR-PM-KING-08',
                'image_url' => 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=900&q=85',
                'images' => [
                    'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=900&q=85',
                    'https://images.unsplash.com/photo-1511886929837-354d827aae26?auto=format&fit=crop&w=900&q=85',
                ],
                'colors' => ['Black', 'Gold'],
                'sizes' => ['39', '40', '41', '42'],
                'description' => 'Chất liệu K-BETTER không nguồn gốc động vật, vượt trội về độ bền và cảm giác kiểm soát bóng êm ái phong cách cổ điển sang trọng.',
            ],
            [
                'id' => 9,
                'name' => 'Mizuno Alpha Japan FG',
                'brand' => 'Mizuno',
                'category_id' => 1,
                'price' => 5200000,
                'old_price' => 5800000,
                'tag' => 'NEW',
                'stock' => 14,
                'sku' => 'STR-MZ-ALPHA-09',
                'image_url' => 'https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&w=900&q=85',
                'images' => [
                    'https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&w=900&q=85',
                    'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?auto=format&fit=crop&w=900&q=85',
                ],
                'colors' => ['Ignition Red', 'White'],
                'sizes' => ['39', '40', '41', '42', '43'],
                'description' => 'Mẫu giày tốc độ đỉnh cao của Mizuno sản xuất tại Nhật Bản, sợi dệt 5 lớp siêu nhẹ kết hợp đệm bọt Mizuno Enerzy bứt tốc mạnh mẽ.',
            ],
            [
                'id' => 10,
                'name' => 'Adidas Copa Pure II.1 FG',
                'brand' => 'Adidas',
                'category_id' => 1,
                'price' => 3650000,
                'old_price' => 4190000,
                'tag' => 'HOT',
                'stock' => 22,
                'sku' => 'STR-AD-COPA-10',
                'image_url' => 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=900&q=85',
                'images' => [
                    'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=900&q=85',
                    'https://images.unsplash.com/photo-1553778263-73a83bab9b0c?auto=format&fit=crop&w=900&q=85',
                ],
                'colors' => ['Cloud White', 'Lucid Blue'],
                'sizes' => ['39', '40', '41', '42', '43'],
                'description' => 'Phần mũi giày Fusionskin da bò cao cấp liền mạch, mang lại cảm giác bóng mềm mại cùng bộ đế Torsionframe ổn định tuyệt đối.',
            ],

            // ==========================================
            // 2. BÓNG THI ĐẤU (Category ID: 2)
            // ==========================================
            [
                'id' => 11,
                'name' => 'Bóng Thi Đấu Nike Flight FIFA Quality Pro',
                'brand' => 'Nike',
                'category_id' => 2,
                'price' => 3290000,
                'old_price' => 3690000,
                'tag' => 'BEST SELLER',
                'stock' => 30,
                'sku' => 'STR-NK-BALL-11',
                'image_url' => 'https://images.unsplash.com/photo-1551958219-acbc608c6377?auto=format&fit=crop&w=900&q=85',
                'images' => [
                    'https://images.unsplash.com/photo-1551958219-acbc608c6377?auto=format&fit=crop&w=900&q=85',
                    'https://images.unsplash.com/photo-1614632537423-1e6c2e7e0aab?auto=format&fit=crop&w=900&q=85',
                ],
                'colors' => ['White/Volt', 'White/Orange'],
                'sizes' => ['Size 5'],
                'description' => 'Công nghệ Aerowsculpt với rãnh đúc khí động học giúp ổn định quỹ đạo bay đến 30%, bóng thi đấu chính thức tiêu chuẩn FIFA Quality Pro.',
            ],
            [
                'id' => 12,
                'name' => 'Bóng Thi Đấu Adidas UCL Pro 24/25 Champions League',
                'brand' => 'Adidas',
                'category_id' => 2,
                'price' => 3490000,
                'old_price' => 3990000,
                'tag' => 'HOT',
                'stock' => 25,
                'sku' => 'STR-AD-UCL-12',
                'image_url' => 'https://images.unsplash.com/photo-1614632537423-1e6c2e7e0aab?auto=format&fit=crop&w=900&q=85',
                'images' => [
                    'https://images.unsplash.com/photo-1614632537423-1e6c2e7e0aab?auto=format&fit=crop&w=900&q=85',
                    'https://images.unsplash.com/photo-1551958219-acbc608c6377?auto=format&fit=crop&w=900&q=85',
                ],
                'colors' => ['Stars White/Cyan', 'Stars Gold'],
                'sizes' => ['Size 5'],
                'description' => 'Trái bóng thi đấu chính thức UEFA Champions League với kết cấu không đường may nhiệt kết dính (thermal bonded) chống thấm nước tuyệt đối.',
            ],
            [
                'id' => 13,
                'name' => 'Bóng Thi Đấu Puma Orbita La Liga 1 FIFA Pro',
                'brand' => 'Puma',
                'category_id' => 2,
                'price' => 2850000,
                'old_price' => 3200000,
                'tag' => 'NEW',
                'stock' => 20,
                'sku' => 'STR-PM-ORB-13',
                'image_url' => 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=900&q=85',
                'images' => [
                    'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=900&q=85',
                    'https://images.unsplash.com/photo-1551958219-acbc608c6377?auto=format&fit=crop&w=900&q=85',
                ],
                'colors' => ['White/Lemon Yellow', 'Orange'],
                'sizes' => ['Size 5'],
                'description' => 'Bóng thi đấu chính thức giải bóng đá La Liga Tây Ban Nha, cấu trúc 12 miếng ghép sâu giúp giữ áp suất và hình dáng bóng hoàn hảo.',
            ],
            [
                'id' => 14,
                'name' => 'Bóng Futsal Động Lực FIFA Quality Pro UHV 2.05',
                'brand' => 'Striker',
                'category_id' => 2,
                'price' => 890000,
                'old_price' => 1050000,
                'tag' => 'BEST SELLER',
                'stock' => 50,
                'sku' => 'STR-BALL-FUT-14',
                'image_url' => 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=900&q=85',
                'images' => [
                    'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=900&q=85',
                    'https://images.unsplash.com/photo-1551958219-acbc608c6377?auto=format&fit=crop&w=900&q=85',
                ],
                'colors' => ['White/Blue', 'Yellow/Orange'],
                'sizes' => ['Size 4'],
                'description' => 'Bóng futsal độ nảy thấp chuyên dụng cho sàn gỗ và sân cỏ nhân tạo mini, chất liệu da PU cao cấp bền bỉ êm chân.',
            ],

            // ==========================================
            // 3. ÁO ĐẤU (Category ID: 3)
            // ==========================================
            [
                'id' => 15,
                'name' => 'Áo Đấu Real Madrid Home 24/25 Authentic',
                'brand' => 'Adidas',
                'category_id' => 3,
                'price' => 1950000,
                'old_price' => 2300000,
                'tag' => 'BEST SELLER',
                'stock' => 40,
                'sku' => 'STR-JERSEY-RM-15',
                'image_url' => 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=900&q=85',
                'images' => [
                    'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=900&q=85',
                    'https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=900&q=85',
                ],
                'colors' => ['White/Gold', 'Away Orange'],
                'sizes' => ['S', 'M', 'L', 'XL'],
                'description' => 'Áo thi đấu sân nhà Real Madrid mùa giải 2024/2025 phiên bản cầu thủ HEAT.RDY siêu nhẹ, thoát nhiệt thông minh.',
            ],
            [
                'id' => 16,
                'name' => 'Áo Đấu Arsenal Home 24/25 Player Version',
                'brand' => 'Adidas',
                'category_id' => 3,
                'price' => 1890000,
                'old_price' => 2200000,
                'tag' => 'HOT',
                'stock' => 30,
                'sku' => 'STR-JERSEY-ARS-16',
                'image_url' => 'https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=900&q=85',
                'images' => [
                    'https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=900&q=85',
                    'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=900&q=85',
                ],
                'colors' => ['Red/White', 'Third Green'],
                'sizes' => ['S', 'M', 'L', 'XL'],
                'description' => 'Áo pháo thủ Arsenal mùa giải 24/25 với logo khẩu pháo thêu nhiệt tinh tế, sợi dệt công nghệ thoáng khí cao cấp.',
            ],
            [
                'id' => 17,
                'name' => 'Áo Đấu Tuyển Việt Nam Grand Sport Home Đỏ',
                'brand' => 'Striker',
                'category_id' => 3,
                'price' => 850000,
                'old_price' => 990000,
                'tag' => 'HOT',
                'stock' => 60,
                'sku' => 'STR-JERSEY-VN-17',
                'image_url' => 'https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&w=900&q=85',
                'images' => [
                    'https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&w=900&q=85',
                    'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=900&q=85',
                ],
                'colors' => ['Đỏ Quốc Kỳ', 'Trắng Sân Khách'],
                'sizes' => ['S', 'M', 'L', 'XL', 'XXL'],
                'description' => 'Áo thi đấu chính thức của Đội tuyển Quốc gia Việt Nam, biểu tượng ngôi sao vàng và họa tiết rồng chìm oai nghiêm.',
            ],
            [
                'id' => 18,
                'name' => 'Áo Đấu Tuyển Argentina 3 Sao World Cup',
                'brand' => 'Adidas',
                'category_id' => 3,
                'price' => 1990000,
                'old_price' => 2400000,
                'tag' => 'BEST SELLER',
                'stock' => 35,
                'sku' => 'STR-JERSEY-ARG-18',
                'image_url' => 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=900&q=85',
                'images' => [
                    'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=900&q=85',
                    'https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=900&q=85',
                ],
                'colors' => ['Sọc Trắng Xanh', 'Tím Sân Khách'],
                'sizes' => ['S', 'M', 'L', 'XL'],
                'description' => 'Áo đấu đội tuyển Argentina với biểu tượng 3 ngôi sao vô địch World Cup thêu vàng kim sang trọng của Lionel Messi.',
            ],
            [
                'id' => 19,
                'name' => 'Áo Đấu Manchester City Authentic 24/25',
                'brand' => 'Puma',
                'category_id' => 3,
                'price' => 1850000,
                'old_price' => 2150000,
                'tag' => 'NEW',
                'stock' => 28,
                'sku' => 'STR-JERSEY-MC-19',
                'image_url' => 'https://images.unsplash.com/photo-1518091043644-c1d4457512c6?auto=format&fit=crop&w=900&q=85',
                'images' => [
                    'https://images.unsplash.com/photo-1518091043644-c1d4457512c6?auto=format&fit=crop&w=900&q=85',
                    'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=900&q=85',
                ],
                'colors' => ['Xanh Sky Blue', 'Đen Neon'],
                'sizes' => ['S', 'M', 'L', 'XL'],
                'description' => 'Áo đấu nhà vô địch Ngoại Hạng Anh Man City công nghệ ULTRAWEAVE siêu nhẹ chỉ 72 gram, giảm ma sát tối đa khi chạy.',
            ],
            [
                'id' => 20,
                'name' => 'Áo Tập Training Striker Pro Dry-FIT Elite',
                'brand' => 'Striker',
                'category_id' => 3,
                'price' => 450000,
                'old_price' => 590000,
                'tag' => 'SALE',
                'stock' => 80,
                'sku' => 'STR-JERSEY-STK-20',
                'image_url' => 'https://images.unsplash.com/photo-1581655353564-df123a1eb820?auto=format&fit=crop&w=900&q=85',
                'images' => [
                    'https://images.unsplash.com/photo-1581655353564-df123a1eb820?auto=format&fit=crop&w=900&q=85',
                    'https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&w=900&q=85',
                ],
                'colors' => ['Đen Cyber', 'Xanh Lime', 'Xám Bạc'],
                'sizes' => ['M', 'L', 'XL', 'XXL'],
                'description' => 'Áo luyện tập bóng đá thể thao co giãn 4 chiều kháng khuẩn, thấm hút mồ hôi cực nhanh cho các buổi đấu tập cường độ cao.',
            ],

            // ==========================================
            // 4. PHỤ KIỆN (Category ID: 4)
            // ==========================================
            [
                'id' => 21,
                'name' => 'Găng Tay Thủ Môn Adidas Predator Pro Fingersave',
                'brand' => 'Adidas',
                'category_id' => 4,
                'price' => 2690000,
                'old_price' => 3100000,
                'tag' => 'BEST SELLER',
                'stock' => 20,
                'sku' => 'STR-GLV-AD-21',
                'image_url' => 'https://images.unsplash.com/photo-1589487391730-58f20eb2c308?auto=format&fit=crop&w=900&q=85',
                'images' => [
                    'https://images.unsplash.com/photo-1589487391730-58f20eb2c308?auto=format&fit=crop&w=900&q=85',
                    'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=900&q=85',
                ],
                'colors' => ['Black/Solar Red', 'White/Blue'],
                'sizes' => ['Size 8', 'Size 9', 'Size 10'],
                'description' => 'Găng tay thủ môn chuyên nghiệp có khung xương chống lật ngón Fingersave, mặt mút URG 2.0 dính bóng siêu việt kể cả trời mưa.',
            ],
            [
                'id' => 22,
                'name' => 'Bọc Ống Đồng Carbon Nike Mercurial Lite Guard',
                'brand' => 'Nike',
                'category_id' => 4,
                'price' => 490000,
                'old_price' => 590000,
                'tag' => 'HOT',
                'stock' => 55,
                'sku' => 'STR-GUARD-NK-22',
                'image_url' => 'https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=900&q=85',
                'images' => [
                    'https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=900&q=85',
                    'https://images.unsplash.com/photo-1511886929837-354d827aae26?auto=format&fit=crop&w=900&q=85',
                ],
                'colors' => ['Đen Carbon', 'Trắng Xanh'],
                'sizes' => ['S', 'M', 'L'],
                'description' => 'Ốp bảo vệ cẳng chân sợi carbon siêu nhẹ chịu lực va đập cao, tặng kèm bao tất dệt ôm sát chân chống xô lệch.',
            ],
            [
                'id' => 23,
                'name' => 'Tất Dệt Kim Thể Thao Chống Trượt Striker GripPro',
                'brand' => 'Striker',
                'category_id' => 4,
                'price' => 120000,
                'old_price' => 150000,
                'tag' => 'BEST SELLER',
                'stock' => 150,
                'sku' => 'STR-SOCK-STK-23',
                'image_url' => 'https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?auto=format&fit=crop&w=900&q=85',
                'images' => [
                    'https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?auto=format&fit=crop&w=900&q=85',
                    'https://images.unsplash.com/photo-1511886929837-354d827aae26?auto=format&fit=crop&w=900&q=85',
                ],
                'colors' => ['Trắng', 'Đen', 'Đỏ', 'Xanh Dương'],
                'sizes' => ['Freesize 38-44'],
                'description' => 'Mặt đáy đệm cao su silicon hình chữ nhật chống trượt chân trong giày khi bứt tốc và đổi hướng đột ngột, thoáng khí êm chân.',
            ],
            [
                'id' => 24,
                'name' => 'Túi Đựng Giày Thể Thao Chống Nước Striker BootBag',
                'brand' => 'Striker',
                'category_id' => 4,
                'price' => 250000,
                'old_price' => 320000,
                'tag' => 'NEW',
                'stock' => 60,
                'sku' => 'STR-BAG-STK-24',
                'image_url' => 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=85',
                'images' => [
                    'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=85',
                    'https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?auto=format&fit=crop&w=900&q=85',
                ],
                'colors' => ['Đen Nhám', 'Xanh Rêu'],
                'sizes' => ['Standard'],
                'description' => 'Túi đựng giày 2 ngăn chuyên dụng có lỗ thông khí khử mùi hôi, chất vải Poly Oxford 900D chống thấm nước hiệu quả.',
            ],
        ];

        foreach ($productsData as $data) {
            $product = Product::updateOrCreate(
                ['id' => $data['id']],
                [
                    'name' => $data['name'],
                    'slug' => Str::slug($data['name']),
                    'sku' => $data['sku'],
                    'brand' => $data['brand'],
                    'tag' => $data['tag'] ?? null,
                    'category_id' => $data['category_id'],
                    'price' => $data['price'],
                    'old_price' => $data['old_price'],
                    'stock' => $data['stock'],
                    'image_url' => $data['image_url'],
                    'images' => $data['images'],
                    'colors' => $data['colors'],
                    'sizes' => $data['sizes'],
                    'description' => $data['description'],
                    'is_active' => true,
                ]
            );

            // Seed Product Images
            ProductImage::where('product_id', $product->id)->delete();
            foreach ($data['images'] as $idx => $img) {
                ProductImage::create([
                    'product_id' => $product->id,
                    'image_path' => $img,
                    'is_primary' => $idx === 0,
                    'sort_order' => $idx,
                ]);
            }

            // Seed Product Variants
            ProductVariant::where('product_id', $product->id)->delete();
            foreach ($data['sizes'] as $size) {
                foreach ($data['colors'] as $color) {
                    $variantSku = sprintf('%s-%s-%s', $data['sku'], Str::slug($size), strtoupper(Str::slug($color)));
                    ProductVariant::create([
                        'product_id' => $product->id,
                        'sku' => $variantSku,
                        'price' => $data['price'],
                        'sale_price' => $data['price'],
                        'stock' => intdiv($data['stock'], max(1, count($data['sizes']) * count($data['colors']))) + 2,
                        'attributes' => [
                            'size' => $size,
                            'color' => $color,
                        ],
                        'is_active' => true,
                    ]);
                }
            }
        }
    }
}
